# configuration.yaml
application_port: 8080
database:
  username: "postgres"
  password: "password"
  authentication: "localhost"
  server_name: "localhost"
  database_name: "newsletter"
  connection_string: "Server=127.0.0.1\\mssqlserver19,1443;Database=AuthLogs;User Id=SA;Password=P4ssw0rd!;Encrypt=True;TrustServerCertificate=True;"