# configuration.yaml
application_port: 8080
database:
  username: "SA"
  password: "P4ssw0rd"
  authentication: "localhost"
  port: 1433
  server_name: "127.0.0.1\\mssqlserver19"
  database_name: "AuthLogs"
  connection_string: "Server=127.0.0.1\\mssqlserver19,1443;Database=AuthLogs;User Id=SA;Password=P4ssw0rd!;Encrypt=True;TrustServerCertificate=True;"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000